-- Complete database schema for Employee Management System (EMS)
-- Generated from JPA entity mappings in src/main/java/com/ems/entity

DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS system_config;
DROP TABLE IF EXISTS security_groups;
DROP TABLE IF EXISTS profile_change_requests;
DROP TABLE IF EXISTS performance_reviews;
DROP TABLE IF EXISTS payroll;
DROP TABLE IF EXISTS leave_policies;
DROP TABLE IF EXISTS leave_balances;
DROP TABLE IF EXISTS leaves;
DROP TABLE IF EXISTS holidays;
DROP TABLE IF EXISTS expense_claims;
DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS shifts;
DROP TABLE IF EXISTS audit_logs;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    manager_id BIGINT
);

CREATE TABLE shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    grace_period_minutes INTEGER NOT NULL
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255),
    job_title VARCHAR(255),
    hire_date DATE,
    salary DOUBLE,
    status VARCHAR(255) NOT NULL,
    photo_path VARCHAR(255),
    department_id BIGINT,
    manager_id BIGINT,
    shift_id BIGINT,
    allowance_rate DOUBLE,
    deduction_rate DOUBLE
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    date DATE NOT NULL,
    check_in TIMESTAMP,
    check_out TIMESTAMP,
    status VARCHAR(255) NOT NULL,
    notes VARCHAR(255),
    CONSTRAINT UK_attendance_employee_date UNIQUE (employee_id, date)
);

CREATE TABLE expense_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    amount DOUBLE NOT NULL,
    category VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    claim_date DATE NOT NULL,
    approved_by BIGINT,
    comments VARCHAR(255)
);

CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    name VARCHAR(255)
);

CREATE TABLE leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(255) NOT NULL,
    balance DOUBLE NOT NULL,
    CONSTRAINT UK_leave_balances_employee_leave_type UNIQUE (employee_id, leave_type)
);

CREATE TABLE leave_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_type VARCHAR(255) NOT NULL UNIQUE,
    annual_allocation DOUBLE NOT NULL,
    monthly_accrual_rate DOUBLE NOT NULL
);

CREATE TABLE leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    approved_by BIGINT,
    comments VARCHAR(255)
);

CREATE TABLE payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    pay_period VARCHAR(255) NOT NULL,
    basic_salary DOUBLE NOT NULL,
    allowances DOUBLE,
    deductions DOUBLE,
    net_salary DOUBLE NOT NULL,
    status VARCHAR(255) NOT NULL,
    processed_date DATE,
    CONSTRAINT UK_payroll_employee_pay_period UNIQUE (employee_id, pay_period)
);

CREATE TABLE performance_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    review_date DATE NOT NULL,
    kpi_goals VARCHAR(255),
    rating INTEGER NOT NULL,
    comments VARCHAR(255),
    promotion_recommendation BOOLEAN
);

CREATE TABLE profile_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    requested_fields_json VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    processed_by BIGINT,
    processed_at TIMESTAMP,
    comments VARCHAR(255)
);

CREATE TABLE system_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value VARCHAR(2000) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE security_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    employee_id BIGINT,
    active BOOLEAN NOT NULL
);

CREATE TABLE user_groups (
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, group_id)
);

ALTER TABLE departments
    ADD CONSTRAINT FK_departments_manager FOREIGN KEY (manager_id) REFERENCES employees(id);

ALTER TABLE employees
    ADD CONSTRAINT FK_employees_department FOREIGN KEY (department_id) REFERENCES departments(id),
    ADD CONSTRAINT FK_employees_manager FOREIGN KEY (manager_id) REFERENCES employees(id),
    ADD CONSTRAINT FK_employees_shift FOREIGN KEY (shift_id) REFERENCES shifts(id);

ALTER TABLE attendance
    ADD CONSTRAINT FK_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

ALTER TABLE expense_claims
    ADD CONSTRAINT FK_expense_claims_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    ADD CONSTRAINT FK_expense_claims_approved_by FOREIGN KEY (approved_by) REFERENCES employees(id);

ALTER TABLE leave_balances
    ADD CONSTRAINT FK_leave_balances_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

ALTER TABLE leaves
    ADD CONSTRAINT FK_leaves_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    ADD CONSTRAINT FK_leaves_approved_by FOREIGN KEY (approved_by) REFERENCES employees(id);

ALTER TABLE payroll
    ADD CONSTRAINT FK_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

ALTER TABLE performance_reviews
    ADD CONSTRAINT FK_performance_reviews_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    ADD CONSTRAINT FK_performance_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES employees(id);

ALTER TABLE profile_change_requests
    ADD CONSTRAINT FK_profile_change_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    ADD CONSTRAINT FK_profile_change_requests_processed_by FOREIGN KEY (processed_by) REFERENCES employees(id);

ALTER TABLE users
    ADD CONSTRAINT FK_users_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

ALTER TABLE user_groups
    ADD CONSTRAINT FK_user_groups_user FOREIGN KEY (user_id) REFERENCES users(id),
    ADD CONSTRAINT FK_user_groups_group FOREIGN KEY (group_id) REFERENCES security_groups(id);

ALTER TABLE audit_logs
    ADD CONSTRAINT PK_audit_logs PRIMARY KEY (id);
